### ISSUE TITLE
Create assets and explore Metro Studio

### ISSUE THREAD

**Issue by gacheson** [gacheson/arduino-reference#4]
See if you can come up with a good set of images for the logo, splash screen, and tiles that, as you said, are consistent and not jarring to the eye. I'd appreciate it if you could pitch your findings to us at a meeting (after you're finished, of course).

**App logo:**
Logo.png - 150x150px
Logo44px.png - 44x44px (obvious, right?)
Logo71px.png - 71x71px
SmallLogo.png - 30x30px
StoreLogo.png - 50x50px
WideLogo.png - 310x150px (not sure if metro studio can make non-square images. see if you can anyway)

**Splash screen:**
SplashScreen.png - 620x300px

**Tiles:**
Abacus.png - 256x256px, padding = 35 (don't worry about the name for this one. just give the images a meaningful name and i'll handle hooking them in)

**Comment by jbatman** [comment]
Splash and all logos for the app are done in blue per our conversation

**Comment by gacheson** [comment]
Nice work!
